name: build_and_run
on:
  pull_request:
  push:
    branches: [ main ]
jobs:
  build-test-and-run:
    strategy:
      os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${os}
    steps:
      - uses: actions/checkout@v4
      - name: Build Script
        run: cmake -P build_and_run_project.cmake -DBUILD_TESTS=ON
  welcome:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          pr-message: |
            ðŸŽ‰ Thanks for your first PR!
            - Ensure to assing, tag and comment the PR.
            - Link the issue (if appy).
